/**
 * Generates supabase/seed.sql from data/*.json.
 *
 * Covers reference data we actually have: commodities, commodity_aliases,
 * commodity_units. Locations get a MINIMAL dev bootstrap only (Nigeria + a few
 * Lagos markets) — the full state/LGA/area hierarchy is a separate data task
 * (NBS/INEC admin lists now; geoBoundaries polygons at stage 8).
 *
 * Run: node scripts/generate-seed.mjs   (also acts as a JSON↔schema check)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const read = (p) => JSON.parse(readFileSync(path.join(root, p), 'utf8'));

const commodities = read('data/commodities.json');
const groups = read('data/substitute-groups.json');
const conversions = read('data/unit-conversions.json');

const BASE_UNITS = new Set(['g', 'ml', 'piece']);
const FORMS = new Set(['loose', 'pre_packed', 'bulk']);
const CONF = new Set(['high', 'medium', 'low']);

const errors = [];
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

// --- validate + index groups ------------------------------------------------
const groupById = new Map(groups.groups.map((g) => [g.groupId, g]));
const commodityIds = new Set(commodities.commodities.map((c) => c.id));

for (const g of groups.groups) {
  for (const id of g.commodityIds) {
    if (!commodityIds.has(id)) errors.push(`group ${g.groupId} → unknown commodity ${id}`);
  }
}

// --- commodities -----------------------------------------------------------
const commodityRows = [];
const aliasRows = [];
for (const c of commodities.commodities) {
  if (!BASE_UNITS.has(c.baseUnit)) errors.push(`${c.id}: bad baseUnit ${c.baseUnit}`);
  for (const f of c.purchaseForms) if (!FORMS.has(f)) errors.push(`${c.id}: bad purchaseForm ${f}`);
  if (c.substituteGroup && !groupById.has(c.substituteGroup)) {
    errors.push(`${c.id}: dangling substituteGroup ${c.substituteGroup}`);
  }
  commodityRows.push(
    `  (${q(c.id)}, ${q(c.canonicalName)}, ${q(c.category)}, ${q(c.baseUnit)}, ` +
      `${c.substituteGroup ? q(c.substituteGroup) : 'NULL'}, ${!!c.perishable}, ` +
      `${!!c.gradeSensitive}, ${!!c.nbsHfcpMapped})`,
  );
  for (const a of c.aliases ?? []) aliasRows.push(`  (${q(c.id)}, ${q(a)})`);
}

// --- commodity_units -----------------------------------------------------------
const unitRows = [];
for (const u of conversions.conversions) {
  if (!BASE_UNITS.has(u.toBaseUnit)) errors.push(`${u.id}: bad toBaseUnit ${u.toBaseUnit}`);
  if (!CONF.has(u.confidence)) errors.push(`${u.id}: bad confidence ${u.confidence}`);
  if (u.gradeSensitive && u.confidence === 'high') errors.push(`${u.id}: gradeSensitive + high`);
  const scope = u.scope === '*' ? 'NULL' : q(u.scope);
  if (u.scope !== '*' && !commodityIds.has(u.scope)) errors.push(`${u.id}: unknown scope ${u.scope}`);
  unitRows.push(
    `  (${q(u.id)}, ${q(u.fromUnit)}, ${q(u.toBaseUnit)}, ${scope}, ` +
      `${u.factorNum}, ${u.factorDen}, ${q(u.confidence)}, ${!!u.gradeSensitive}, ` +
      `${u.note ? q(u.note) : 'NULL'})`,
  );
}

if (errors.length) {
  console.error('SEED VALIDATION FAILED:\n' + errors.map((e) => '  - ' + e).join('\n'));
  process.exit(1);
}

// --- emit ----------------------------------------------------------------------
const sql = `-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Source: data/commodities.json, data/substitute-groups.json, data/unit-conversions.json
BEGIN;

-- Minimal locations bootstrap (dev). Replace with the full admin hierarchy.
INSERT INTO locations (id, level, name, market_type) VALUES
  ('11111111-1111-1111-1111-111111111111', 'country', 'Nigeria', 'unknown')
ON CONFLICT (id) DO NOTHING;
INSERT INTO locations (id, level, name, parent_id, country_id, state_id, market_type) VALUES
  ('22222222-2222-2222-2222-222222222222', 'state', 'Lagos',
   '11111111-1111-1111-1111-111111111111', '11111111-1111-1111-1111-111111111111',
   '22222222-2222-2222-2222-222222222222', 'unknown')
ON CONFLICT (id) DO NOTHING;
INSERT INTO locations (id, level, name, parent_id, country_id, state_id, market_type) VALUES
  ('33333333-3333-3333-3333-333333333333', 'market', 'Mile 12 Market',
   '22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111',
   '22222222-2222-2222-2222-222222222222', 'open_market'),
  ('44444444-4444-4444-4444-444444444444', 'market', 'Oyingbo Market',
   '22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111',
   '22222222-2222-2222-2222-222222222222', 'open_market'),
  ('55555555-5555-5555-5555-555555555555', 'market', 'Shoprite Ikeja',
   '22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111',
   '22222222-2222-2222-2222-222222222222', 'supermarket')
ON CONFLICT (id) DO NOTHING;

INSERT INTO commodities
  (id, canonical_name, category, base_unit, substitute_group, perishable, grade_sensitive, nbs_hfcp_mapped)
VALUES
${commodityRows.join(',\n')}
ON CONFLICT (id) DO UPDATE SET
  canonical_name = EXCLUDED.canonical_name, category = EXCLUDED.category,
  base_unit = EXCLUDED.base_unit, substitute_group = EXCLUDED.substitute_group,
  perishable = EXCLUDED.perishable, grade_sensitive = EXCLUDED.grade_sensitive,
  nbs_hfcp_mapped = EXCLUDED.nbs_hfcp_mapped;

DELETE FROM commodity_aliases;
INSERT INTO commodity_aliases (commodity_id, alias) VALUES
${aliasRows.join(',\n')}
ON CONFLICT DO NOTHING;

INSERT INTO commodity_units
  (id, unit_code, to_base_unit, commodity_id, factor_num, factor_den, confidence, grade_sensitive, note)
VALUES
${unitRows.join(',\n')}
ON CONFLICT (id) DO UPDATE SET
  factor_num = EXCLUDED.factor_num, factor_den = EXCLUDED.factor_den,
  confidence = EXCLUDED.confidence, grade_sensitive = EXCLUDED.grade_sensitive,
  note = EXCLUDED.note;

COMMIT;
`;

writeFileSync(path.join(root, 'supabase/seed.sql'), sql);
console.log(
  `seed.sql written: ${commodityRows.length} commodities, ${aliasRows.length} aliases, ${unitRows.length} conversions`,
);
